DotNet_V22/ORMS/Chefs_Dishes/Models/ChefModel.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace ChefDishes.Models;

using ChefDishes.Lib;
public class Chef
{
    [Key]
    public int ChefId { get; set; }

    [Required(ErrorMessage = "First Name is required")]
    [MinLength(2, ErrorMessage = "First Name must be at least 2 characters")]
    public string FirstName { get; set; }

    [Required(ErrorMessage = "Last Name is required")]
    [MinLength(2, ErrorMessage = "Last Name must be at least 2 characters")]
    public string LastName { get; set; }

    [Required(ErrorMessage = "Birthdate is required")]
    [AtLeastEighteen]
    public DateTime? Birthday { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    public List<Dish>? Dishes { get; set; } = new List<Dish>();
}

DotNet_V22/ORMS/Chefs_Dishes/Models/ChefViewModel.cs
public class ChefViewModel
{
    public ChefViewModel(string fullName, int age, int numOfDishes)
    {
        FullName = fullName;
        Age = age;
        NumOfDishes = numOfDishes;
    }
    public string FullName { get; set; }
    public int Age { get; set; }
    public int NumOfDishes { get; set; }
}

DotNet_V22/ORMS/Chefs_Dishes/Models/DBRepository.cs
#pragma warning disable CS8618
// We can disable our warnings safely because we know the framework will assign non-null values 
// when it constructs this class for us.
using Microsoft.EntityFrameworkCore;
namespace ChefDishes.Models;
// the MyContext class represents a session with our MySQL database, allowing us to query for or save data
// DbContext is a class that comes from EntityFramework, we want to inherit its features
public class DBRepository : DbContext
{
    // This line will always be here. It is what constructs our context upon initialization  
    public DBRepository(DbContextOptions options) : base(options) { }
    // We need to create a new DbSet<Model> for every model in our project that is making a table
    // The name of our table in our database will be based on the name we provide here
    // This is where we provide a plural version of our model to fit table naming standards    
    public DbSet<Chef> Chefs { get; set; }
    public DbSet<Dish> Dishes { get; set; }
}

DotNet_V22/ORMS/Chefs_Dishes/Models/DishModel.cs
using System.ComponentModel.DataAnnotations;
namespace ChefDishes.Models;
public class Dish
{
    [Key]
    public int DishId { get; set; }
    [Required(ErrorMessage = "Name is required")]
    [MinLength(3, ErrorMessage = "Name must be at least 3 characters")]
    [MaxLength(50, ErrorMessage = "Name cannot be more than 50 characters")]
    public string Name { get; set; } 

    [Required(ErrorMessage = "Tastiness is required")]
    [Range(1, 5, ErrorMessage = "Tastiness must be between 1 and 5")]
    public int Tastiness { get; set; }
    
    [Required(ErrorMessage = "Calories are required")]
    [Range(1, int.MaxValue, ErrorMessage = "Calories must be greater than 0")]
    public int? Calories { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;

    [Required(ErrorMessage = "Chef is required")]
    public int ChefId { get; set; }

    public Chef? Creator { get; set; }
}

DotNet_V22/ORMS/Chefs_Dishes/Models/DishViewModel.cs
public class DishViewModel
{
    public DishViewModel(string name, string chefFullName, int tastiness, int calories)
    {
        Name = name;
        ChefFullName = chefFullName;
        Tastiness = tastiness;
        Calories = calories;
    }
    public string Name { get; set; }
    public string ChefFullName { get; set; }
    public int Tastiness { get; set; }
    public int Calories { get; set; }
}

DotNet_V22/ORMS/Chefs_Dishes/Models/ErrorViewModel.cs
namespace ChefDishes.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotNet_V22/ORMS/Chefs_Dishes/Controllers/ChefController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ChefDishes.Models;
using Microsoft.AspNetCore.Identity;

using ChefDishes.Lib;

namespace ChefDishes.Controllers
{
    [Route("chefs")]
    public class ChefController : Controller
    {
        private DBRepository db;
        private readonly ILogger<ChefController> _logger;

        public ChefController(ILogger<ChefController> logger, DBRepository context)
        {
            _logger = logger;
            db = context;
        }

        [HttpGet("new")]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost("create")]
        public IActionResult Create(Chef chef)
        {
            if (ModelState.IsValid)
            {
                db.Add(chef);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View("New");
        }

    }
}

DotNet_V22/ORMS/Chefs_Dishes/Controllers/DishController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ChefDishes.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

using ChefDishes.Lib;

namespace ChefDishes.Controllers
{
    [Route("dishes")]
    public class DishController : Controller
    {
        private DBRepository db;
        private readonly ILogger<DishController> _logger;

        public DishController(ILogger<DishController> logger, DBRepository context)
        {
            _logger = logger;
            db = context;
        }

        public IActionResult Index()
        {
            List<DishViewModel> dishes = db.Dishes
                .Include(d => d.Creator)
                .Select(d => new DishViewModel
                (
                    d.Name,
                    d.Creator.FirstName + " " + d.Creator.LastName,
                    d.Tastiness,
                    d.Calories.Value
                )).ToList();

            return View(dishes);
        }

        [HttpGet("new")]
        public IActionResult New()
        {
            ViewBag.Chefs = db.Chefs
                .Select(c => new
                {
                    ChefId = c.ChefId,
                    FullName = c.FirstName + " " + c.LastName
                }).ToList();

            return View();
        }

        [HttpPost("create")]
        public IActionResult Create(Dish chef)
        {
            if (ModelState.IsValid)
            {
                db.Add(chef);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Chefs = db.Chefs
                .Select(c => new
                {
                    ChefId = c.ChefId,
                    FullName = c.FirstName + " " + c.LastName
                }).ToList();
            return View("New");
        }

    }
}

DotNet_V22/ORMS/Chefs_Dishes/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ChefDishes.Models;
using Microsoft.AspNetCore.Identity;

using ChefDishes.Lib;

namespace ChefDishes.Controllers
{
    public class HomeController : Controller
    {
        private DBRepository db;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, DBRepository context)
        {
            _logger = logger;
            db = context;
        }

        public IActionResult Index()
        {

            List<ChefViewModel> chefs = db.Chefs.Select(c => new ChefViewModel
                (
                    c.FirstName + " " + c.LastName,
                    DateTime.Now.Year - c.Birthday.Value.Year - (DateTime.Now.DayOfYear < c.Birthday.Value.DayOfYear ? 1 : 0),
                    c.Dishes.Count
                )).ToList();

            return View(chefs);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

DotNet_V22/ORMS/Chefs_Dishes/Views/Dish/Index.cshtml
@{
    ViewData["Title"] = "Dishes";
}

@model List<DishViewModel>

<div class="container mx-auto">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-800">
            <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Dish Name</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Chef</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Tastiness</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Calories</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            @foreach (var dish in Model)
            {
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@dish.Name</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@dish.ChefFullName</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@dish.Tastiness</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@dish.Calories</td>
                </tr>
            }
        </tbody>
    </table>
</div>

DotNet_V22/ORMS/Chefs_Dishes/Views/Dish/New.cshtml
@{
    ViewData["Title"] = "Create Dish";
}

@model Dish

<form asp-controller="Dish" asp-action="Create" method="post">
    <div class="bg-white rounded shadow-lg p-8">
        <h1 class="block w-full text-center text-gray-800 text-2xl font-bold mb-6">Create Dish</h1>
        <div class="grid mb-4">
            <label class="mb-2 font-bold text-lg text-gray-700" for="Name">Dish Name</label>
            <input asp-for="Name" class="border py-2 px-3 text-grey-darkest" />
            <span class="text-red-500" asp-validation-for="Name"></span>
        </div>
        <div class="grid mb-4">
            <label class="mb-2 font-bold text-lg text-gray-700" for="ChefId">Chef</label>
            <select  asp-for="ChefId" class="border py-2 px-3 text-grey-darkest">
                @foreach (var chef in ViewBag.Chefs)
                {
                    <option value="@chef.ChefId">@chef.FullName</option>
                }
            </select>
             <span class="text-red-500" asp-validation-for="ChefId"></span>
        </div>
        <div class="grid mb-4">
            <label class="mb-2 font-bold text-lg text-gray-700" for="Tastiness">Tastiness</label>
            <select asp-for="Tastiness" class="border py-2 px-3 text-grey-darkest">
                <option value="-1">Select Tastiness</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            <span class="text-red-500" asp-validation-for="Tastiness"></span>
        </div>
        <div class="grid mb-4">
            <label class="mb-2 font-bold text-lg text-gray-700" for="Calories">Calories</label>
            <input asp-for="Calories" class="border py-2 px-3 text-grey-darkest">
            <span class="text-red-500" asp-validation-for="Calories"></span>
        </div>
        <button class="w-full bg-blue-500 hover:bg-blue-600 text-white uppercase text-lg mx-auto p-2 rounded" type="submit">Create Dish</button>
    </div>
</form>

DotNet_V22/ORMS/Chefs_Dishes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<ChefViewModel>

<div class="container mx-auto">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-800">
            <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Full Name</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Age</th>
                <th class="px-6 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">Number of Dishes</th>
            </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
            @foreach (var chef in Model)
            {
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@chef.FullName</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@chef.Age</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm text-black">@chef.NumOfDishes</td>
                </tr>
            }
        </tbody>
    </table>
</div>

DotNet_V22/ORMS/Chefs_Dishes/Views/Home/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<form asp-controller="Home" asp-action="Logout" asp-route-userId="@Context.Session.GetInt32("uid") method="post">
    <button type="submit" class="btn bg-blue-500 hover:bg-blue-700">Logout</button>
</form>

<h1 class="p-96 text-5xl">Success!</h1>